# Custom Language File for Launcher Customizer

[ejs.app]
title = "S.M.P Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/FoudreTeam/foudresmplauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "http://discord.foudremagic.fr"

[ejs.settings]
sourceGithubLink = "https://github.com/FoudreTeam/foudresmplauncher"
supportLink = "https://github.com/FoudreTeam/foudresmplauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le S.M.P ()"
welcomeDescription = "Serveur SMP moddé créé par Parada avec l'aide de Foudremagic."
welcomeDescCTA = "Serveur sous whitelist."
